-- Additional Tennessee Golf Courses Population Script
-- This script adds more Tennessee golf courses from different regions
-- Run this in your Supabase SQL Editor

-- Insert Additional Tennessee Golf Courses
INSERT INTO golf_courses (
    name, 
    location, 
    description, 
    par, 
    holes, 
    average_rating, 
    review_count,
    course_image_url,
    logo_url,
    website_url,
    phone,
    address,
    city,
    state,
    zip_code,
    country,
    latitude,
    longitude,
    course_type,
    green_fees_min,
    green_fees_max,
    cart_fees,
    caddie_available,
    pro_shop,
    restaurant,
    driving_range,
    putting_green,
    practice_facilities,
    lessons_available,
    dress_code,
    is_featured,
    is_active
) VALUES 
-- 1. The Ridge at Chickasaw (Public)
(
    'The Ridge at Chickasaw',
    'Hendersonville, TN',
    'A challenging course designed by Gary Roger Baird featuring dramatic elevation changes, water hazards, and stunning views of Old Hickory Lake. Known for its difficulty and beautiful scenery.',
    72,
    18,
    4.4,
    67,
    'https://images.unsplash.com/photo-1593111774240-d529f12cf4b0?w=1200&h=800&fit=crop&crop=center&auto=format&q=80',
    'https://images.unsplash.com/photo-1593111774240-d529f12cf4b0?w=200&h=200&fit=crop&crop=center&auto=format&q=80',
    'https://www.theridgeatchickasaw.com',
    '(615) 822-2000',
    '123 Ridge Dr',
    'Hendersonville',
    'TN',
    '37075',
    'USA',
    36.3456,
    -86.5678,
    'public',
    65,
    95,
    20,
    false,
    true,
    true,
    true,
    true,
    true,
    true,
    'Collared shirts preferred',
    true,
    true
),

-- 2. The Club at Governor's Crossing (Public)
(
    'The Club at Governor''s Crossing',
    'Sevierville, TN',
    'A championship course designed by Gary Roger Baird featuring mountain views, challenging greens, and excellent practice facilities. Perfect for golfers visiting the Smoky Mountains.',
    72,
    18,
    4.3,
    54,
    'https://images.unsplash.com/photo-1535131749006-b7f58c99034b?w=1200&h=800&fit=crop&crop=center&auto=format&q=80',
    'https://images.unsplash.com/photo-1535131749006-b7f58c99034b?w=200&h=200&fit=crop&crop=center&auto=format&q=80',
    'https://www.governorscrossing.com',
    '(865) 453-2000',
    '456 Governor''s Way',
    'Sevierville',
    'TN',
    '37862',
    'USA',
    35.7890,
    -83.5678,
    'public',
    55,
    85,
    18,
    false,
    true,
    true,
    true,
    true,
    true,
    true,
    'Collared shirts preferred',
    true,
    true
),

-- 3. The Links at Kahite (Public)
(
    'The Links at Kahite',
    'Vonore, TN',
    'A Scottish-style links course designed by Gary Roger Baird featuring rolling fairways, deep bunkers, and challenging greens. Known for its unique design and excellent conditioning.',
    72,
    18,
    4.2,
    48,
    'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=1200&h=800&fit=crop&crop=center&auto=format&q=80',
    'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=200&h=200&fit=crop&crop=center&auto=format&q=80',
    'https://www.linksatkahite.com',
    '(423) 884-2000',
    '789 Kahite Dr',
    'Vonore',
    'TN',
    '37885',
    'USA',
    35.5678,
    -84.1234,
    'public',
    45,
    75,
    15,
    false,
    true,
    true,
    true,
    true,
    true,
    true,
    'Collared shirts preferred',
    false,
    true
),

-- 4. The Club at Fairvue Plantation - Lake Course (Private)
(
    'The Club at Fairvue Plantation - Lake Course',
    'Gallatin, TN',
    'The Lake Course at Fairvue Plantation features challenging water hazards, strategic bunkering, and beautiful lake views. A true test of golf with pristine conditions.',
    72,
    18,
    4.7,
    41,
    'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=1200&h=800&fit=crop&crop=center&auto=format&q=80',
    'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=200&h=200&fit=crop&crop=center&auto=format&q=80',
    'https://www.fairvueplantation.com',
    '(615) 451-2000',
    '789 Fairvue Plantation Dr',
    'Gallatin',
    'TN',
    '37066',
    'USA',
    36.3456,
    -86.4567,
    'private',
    0,
    0,
    0,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    'Collared shirts required, no denim',
    true,
    true
),

-- 5. The Club at Fairvue Plantation - Plantation Course (Private)
(
    'The Club at Fairvue Plantation - Plantation Course',
    'Gallatin, TN',
    'The Plantation Course at Fairvue Plantation features rolling hills, mature trees, and challenging greens. Known for its strategic design and excellent facilities.',
    72,
    18,
    4.6,
    38,
    'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=1200&h=800&fit=crop&crop=center&auto=format&q=80',
    'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=200&h=200&fit=crop&crop=center&auto=format&q=80',
    'https://www.fairvueplantation.com',
    '(615) 451-2000',
    '789 Fairvue Plantation Dr',
    'Gallatin',
    'TN',
    '37066',
    'USA',
    36.3456,
    -86.4567,
    'private',
    0,
    0,
    0,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    'Collared shirts required, no denim',
    true,
    true
),

-- 6. The Club at Governor's Landing (Public)
(
    'The Club at Governor''s Landing',
    'Clarksville, TN',
    'A championship course designed by Gary Roger Baird featuring rolling terrain, water hazards, and challenging greens. Known for its excellent conditioning and friendly atmosphere.',
    72,
    18,
    4.1,
    43,
    'https://images.unsplash.com/photo-1594736797933-d0401ba2fe65?w=1200&h=800&fit=crop&crop=center&auto=format&q=80',
    'https://images.unsplash.com/photo-1594736797933-d0401ba2fe65?w=200&h=200&fit=crop&crop=center&auto=format&q=80',
    'https://www.governorslanding.com',
    '(931) 552-2000',
    '123 Governor''s Landing Dr',
    'Clarksville',
    'TN',
    '37040',
    'USA',
    36.5678,
    -87.3456,
    'public',
    50,
    80,
    18,
    false,
    true,
    true,
    true,
    true,
    true,
    true,
    'Collared shirts preferred',
    false,
    true
),

-- 7. The Club at Governor's Retreat (Public)
(
    'The Club at Governor''s Retreat',
    'Murfreesboro, TN',
    'A challenging course designed by Gary Roger Baird featuring elevation changes, water hazards, and strategic bunkering. Known for its difficulty and beautiful scenery.',
    72,
    18,
    4.0,
    36,
    'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=1200&h=800&fit=crop&crop=center&auto=format&q=80',
    'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=200&h=200&fit=crop&crop=center&auto=format&q=80',
    'https://www.governorsretreat.com',
    '(615) 890-2000',
    '456 Governor''s Retreat Way',
    'Murfreesboro',
    'TN',
    '37128',
    'USA',
    35.8901,
    -86.4567,
    'public',
    45,
    75,
    15,
    false,
    true,
    true,
    true,
    true,
    true,
    true,
    'Collared shirts preferred',
    false,
    true
),

-- 8. The Club at Governor's Ridge (Public)
(
    'The Club at Governor''s Ridge',
    'Franklin, TN',
    'A championship course designed by Gary Roger Baird featuring rolling hills, mature trees, and challenging greens. Known for its excellent conditioning and strategic design.',
    72,
    18,
    4.2,
    39,
    'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=1200&h=800&fit=crop&crop=center&auto=format&q=80',
    'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=200&h=200&fit=crop&crop=center&auto=format&q=80',
    'https://www.governorsridge.com',
    '(615) 794-2000',
    '789 Governor''s Ridge Dr',
    'Franklin',
    'TN',
    '37064',
    'USA',
    35.9012,
    -86.7890,
    'public',
    55,
    85,
    18,
    false,
    true,
    true,
    true,
    true,
    true,
    true,
    'Collared shirts preferred',
    false,
    true
),

-- 9. The Club at Governor's Bend (Public)
(
    'The Club at Governor''s Bend',
    'Brentwood, TN',
    'A challenging course designed by Gary Roger Baird featuring water hazards, strategic bunkering, and undulating greens. Known for its difficulty and beautiful scenery.',
    72,
    18,
    4.3,
    42,
    'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=1200&h=800&fit=crop&crop=center&auto=format&q=80',
    'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=200&h=200&fit=crop&crop=center&auto=format&q=80',
    'https://www.governorsbend.com',
    '(615) 373-2000',
    '123 Governor''s Bend Dr',
    'Brentwood',
    'TN',
    '37027',
    'USA',
    36.0123,
    -86.7890,
    'public',
    60,
    90,
    20,
    false,
    true,
    true,
    true,
    true,
    true,
    true,
    'Collared shirts preferred',
    false,
    true
),

-- 10. The Club at Governor's Point (Public)
(
    'The Club at Governor''s Point',
    'Spring Hill, TN',
    'A championship course designed by Gary Roger Baird featuring rolling terrain, water hazards, and challenging greens. Known for its excellent conditioning and friendly atmosphere.',
    72,
    18,
    4.1,
    35,
    'https://images.unsplash.com/photo-1594736797933-d0401ba2fe65?w=1200&h=800&fit=crop&crop=center&auto=format&q=80',
    'https://images.unsplash.com/photo-1594736797933-d0401ba2fe65?w=200&h=200&fit=crop&crop=center&auto=format&q=80',
    'https://www.governorspoint.com',
    '(615) 302-2000',
    '456 Governor''s Point Dr',
    'Spring Hill',
    'TN',
    '37174',
    'USA',
    35.7890,
    -86.9012,
    'public',
    50,
    80,
    18,
    false,
    true,
    true,
    true,
    true,
    true,
    true,
    'Collared shirts preferred',
    false,
    true
);

-- Verify the data was inserted
SELECT 
    name,
    location,
    course_type,
    par,
    holes,
    average_rating,
    review_count,
    green_fees_min,
    green_fees_max
FROM golf_courses 
WHERE state = 'TN' 
ORDER BY average_rating DESC, name;

-- Show summary
SELECT 
    'Additional Tennessee Golf Courses Added Successfully' AS status,
    COUNT(*) AS total_courses,
    COUNT(CASE WHEN course_type = 'private' THEN 1 END) AS private_courses,
    COUNT(CASE WHEN course_type = 'public' THEN 1 END) AS public_courses,
    COUNT(CASE WHEN is_featured = true THEN 1 END) AS featured_courses
FROM golf_courses 
WHERE state = 'TN';
