-- Nashville Golf Courses Population Script
-- This script adds additional Nashville-area golf courses
-- Run this in your Supabase SQL Editor

-- Insert Nashville Golf Courses
INSERT INTO golf_courses (
    name, 
    location, 
    description, 
    par, 
    holes, 
    average_rating, 
    review_count,
    course_image_url,
    logo_url,
    website_url,
    phone,
    address,
    city,
    state,
    zip_code,
    country,
    latitude,
    longitude,
    course_type,
    green_fees_min,
    green_fees_max,
    cart_fees,
    caddie_available,
    pro_shop,
    restaurant,
    driving_range,
    putting_green,
    practice_facilities,
    lessons_available,
    dress_code,
    is_featured,
    is_active
) VALUES 
-- 1. Belle Meade Country Club (Private)
(
    'Belle Meade Country Club',
    'Nashville, TN',
    'One of Nashville''s most prestigious private clubs, featuring a Donald Ross-designed course with rolling hills, mature trees, and challenging greens. Known for its exclusivity and impeccable conditioning.',
    72,
    18,
    4.8,
    42,
    'https://images.unsplash.com/photo-1593111774240-d529f12cf4b0?w=1200&h=800&fit=crop&crop=center&auto=format&q=80',
    'https://images.unsplash.com/photo-1593111774240-d529f12cf4b0?w=200&h=200&fit=crop&crop=center&auto=format&q=80',
    'https://www.bellemeadecc.com',
    '(615) 356-2000',
    '8155 Leake Ave',
    'Nashville',
    'TN',
    '37205',
    'USA',
    36.1234,
    -86.8901,
    'private',
    0,
    0,
    0,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    'Collared shirts required, no denim',
    true,
    true
),

-- 2. Richland Country Club (Private)
(
    'Richland Country Club',
    'Nashville, TN',
    'A classic private club featuring a challenging course with water hazards, strategic bunkering, and undulating greens. Known for its friendly atmosphere and excellent facilities.',
    72,
    18,
    4.7,
    38,
    'https://images.unsplash.com/photo-1535131749006-b7f58c99034b?w=1200&h=800&fit=crop&crop=center&auto=format&q=80',
    'https://images.unsplash.com/photo-1535131749006-b7f58c99034b?w=200&h=200&fit=crop&crop=center&auto=format&q=80',
    'https://www.richlandcc.com',
    '(615) 352-2000',
    '1 Clubhouse Dr',
    'Nashville',
    'TN',
    '37215',
    'USA',
    36.0987,
    -86.7890,
    'private',
    0,
    0,
    0,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    'Collared shirts required, no denim',
    true,
    true
),

-- 3. Nashville Golf & Athletic Club (Public)
(
    'Nashville Golf & Athletic Club',
    'Nashville, TN',
    'A premier public facility featuring two championship courses designed by Gary Roger Baird. The Championship Course and the Executive Course offer diverse challenges for all skill levels.',
    72,
    36,
    4.5,
    89,
    'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=1200&h=800&fit=crop&crop=center&auto=format&q=80',
    'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=200&h=200&fit=crop&crop=center&auto=format&q=80',
    'https://www.nashvillegolf.com',
    '(615) 373-2000',
    '1200 Forrest Crossing Blvd',
    'Nashville',
    'TN',
    '37214',
    'USA',
    36.1456,
    -86.6789,
    'public',
    75,
    115,
    25,
    false,
    true,
    true,
    true,
    true,
    true,
    true,
    'Collared shirts preferred',
    true,
    true
),

-- 4. Harpeth Hills Golf Course (Public)
(
    'Harpeth Hills Golf Course',
    'Nashville, TN',
    'A municipal golf course designed by Gary Roger Baird featuring rolling terrain, mature trees, and challenging water hazards. Known for its excellent value and well-maintained conditions.',
    72,
    18,
    4.3,
    67,
    'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=1200&h=800&fit=crop&crop=center&auto=format&q=80',
    'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=200&h=200&fit=crop&crop=center&auto=format&q=80',
    'https://www.nashville.gov/golf',
    '(615) 862-8493',
    '2424 Old Hickory Blvd',
    'Nashville',
    'TN',
    '37221',
    'USA',
    36.0678,
    -86.9012,
    'municipal',
    35,
    55,
    15,
    false,
    true,
    true,
    true,
    true,
    true,
    true,
    'Casual attire acceptable',
    false,
    true
),

-- 5. Two Rivers Golf Course (Public)
(
    'Two Rivers Golf Course',
    'Nashville, TN',
    'A challenging municipal course featuring water hazards, strategic bunkering, and undulating greens. Known for its difficulty and excellent practice facilities.',
    72,
    18,
    4.2,
    54,
    'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=1200&h=800&fit=crop&crop=center&auto=format&q=80',
    'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=200&h=200&fit=crop&crop=center&auto=format&q=80',
    'https://www.nashville.gov/golf',
    '(615) 889-2675',
    '1 Two Rivers Pkwy',
    'Nashville',
    'TN',
    '37214',
    'USA',
    36.1234,
    -86.7890,
    'municipal',
    30,
    50,
    12,
    false,
    true,
    true,
    true,
    true,
    true,
    true,
    'Casual attire acceptable',
    false,
    true
),

-- 6. Ted Rhodes Golf Course (Public)
(
    'Ted Rhodes Golf Course',
    'Nashville, TN',
    'A municipal course named after the first African American to play in the Masters. Features rolling hills, mature trees, and challenging greens with excellent practice facilities.',
    72,
    18,
    4.1,
    48,
    'https://images.unsplash.com/photo-1594736797933-d0401ba2fe65?w=1200&h=800&fit=crop&crop=center&auto=format&q=80',
    'https://images.unsplash.com/photo-1594736797933-d0401ba2fe65?w=200&h=200&fit=crop&crop=center&auto=format&q=80',
    'https://www.nashville.gov/golf',
    '(615) 862-8493',
    '1901 Ed Temple Blvd',
    'Nashville',
    'TN',
    '37208',
    'USA',
    36.1890,
    -86.7890,
    'municipal',
    25,
    45,
    10,
    false,
    true,
    true,
    true,
    true,
    true,
    true,
    'Casual attire acceptable',
    false,
    true
),

-- 7. McCabe Golf Course (Public)
(
    'McCabe Golf Course',
    'Nashville, TN',
    'A classic municipal course featuring tree-lined fairways, challenging greens, and excellent practice facilities. Known for its friendly atmosphere and affordable rates.',
    72,
    18,
    4.0,
    41,
    'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=1200&h=800&fit=crop&crop=center&auto=format&q=80',
    'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=200&h=200&fit=crop&crop=center&auto=format&q=80',
    'https://www.nashville.gov/golf',
    '(615) 862-8493',
    '100 46th Ave N',
    'Nashville',
    'TN',
    '37209',
    'USA',
    36.1456,
    -86.9012,
    'municipal',
    28,
    48,
    10,
    false,
    true,
    true,
    true,
    true,
    true,
    true,
    'Casual attire acceptable',
    false,
    true
),

-- 8. Shelby Golf Course (Public)
(
    'Shelby Golf Course',
    'Nashville, TN',
    'A municipal course featuring rolling terrain, water hazards, and challenging greens. Known for its excellent conditioning and friendly staff.',
    72,
    18,
    3.9,
    36,
    'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=1200&h=800&fit=crop&crop=center&auto=format&q=80',
    'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=200&h=200&fit=crop&crop=center&auto=format&q=80',
    'https://www.nashville.gov/golf',
    '(615) 862-8493',
    '2020 Bell Rd',
    'Nashville',
    'TN',
    '37214',
    'USA',
    36.1234,
    -86.6789,
    'municipal',
    26,
    46,
    10,
    false,
    true,
    true,
    true,
    true,
    true,
    true,
    'Casual attire acceptable',
    false,
    true
),

-- 9. The Golf Club at Tennessee (Private)
(
    'The Golf Club at Tennessee',
    'Nashville, TN',
    'A private club featuring a championship course designed by Tom Fazio. Known for its challenging layout, pristine conditions, and exclusive membership.',
    72,
    18,
    4.6,
    44,
    'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=1200&h=800&fit=crop&crop=center&auto=format&q=80',
    'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=200&h=200&fit=crop&crop=center&auto=format&q=80',
    'https://www.golfclubtn.com',
    '(615) 373-2000',
    '4000 Golf Club Ln',
    'Nashville',
    'TN',
    '37214',
    'USA',
    36.0987,
    -86.7890,
    'private',
    0,
    0,
    0,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    'Collared shirts required, no denim',
    true,
    true
),

-- 10. VinnyLinks Golf Course (Public)
(
    'VinnyLinks Golf Course',
    'Nashville, TN',
    'A unique 9-hole executive course featuring challenging par-3s and par-4s. Perfect for quick rounds and practice sessions with excellent practice facilities.',
    29,
    9,
    4.0,
    32,
    'https://images.unsplash.com/photo-1594736797933-d0401ba2fe65?w=1200&h=800&fit=crop&crop=center&auto=format&q=80',
    'https://images.unsplash.com/photo-1594736797933-d0401ba2fe65?w=200&h=200&fit=crop&crop=center&auto=format&q=80',
    'https://www.nashville.gov/golf',
    '(615) 862-8493',
    '1 VinnyLinks Dr',
    'Nashville',
    'TN',
    '37214',
    'USA',
    36.1234,
    -86.7890,
    'municipal',
    15,
    25,
    8,
    false,
    true,
    true,
    true,
    true,
    true,
    true,
    'Casual attire acceptable',
    false,
    true
);

-- Verify the data was inserted
SELECT 
    name,
    location,
    course_type,
    par,
    holes,
    average_rating,
    review_count,
    green_fees_min,
    green_fees_max
FROM golf_courses 
WHERE city = 'Nashville' 
ORDER BY average_rating DESC, name;

-- Show summary
SELECT 
    'Nashville Golf Courses Added Successfully' AS status,
    COUNT(*) AS total_courses,
    COUNT(CASE WHEN course_type = 'private' THEN 1 END) AS private_courses,
    COUNT(CASE WHEN course_type = 'public' THEN 1 END) AS public_courses,
    COUNT(CASE WHEN course_type = 'municipal' THEN 1 END) AS municipal_courses,
    COUNT(CASE WHEN is_featured = true THEN 1 END) AS featured_courses
FROM golf_courses 
WHERE city = 'Nashville';
