-- Canton, Georgia Golf Courses Population Script
-- This script adds golf courses in the Canton, Georgia area
-- Run this in your Supabase SQL Editor

-- Insert Canton, Georgia Golf Courses
INSERT INTO golf_courses (
    name, 
    location, 
    description, 
    par, 
    holes, 
    average_rating, 
    review_count,
    course_image_url,
    logo_url,
    website_url,
    phone,
    address,
    city,
    state,
    zip_code,
    country,
    latitude,
    longitude,
    course_type,
    green_fees_min,
    green_fees_max,
    cart_fees,
    caddie_available,
    pro_shop,
    restaurant,
    driving_range,
    putting_green,
    practice_facilities,
    lessons_available,
    dress_code,
    is_featured,
    is_active
) VALUES 
-- 1. The Club at Lake Arrowhead (Private)
(
    'The Club at Lake Arrowhead',
    'Canton, GA',
    'A premier private golf club featuring two championship courses designed by Joe Lee. The Lakes Course offers stunning water views and challenging play, while the Creeks Course winds through mature hardwoods and rolling terrain.',
    72,
    18,
    4.8,
    89,
    'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=1200&h=800&fit=crop&crop=center&auto=format&q=80',
    'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=200&h=200&fit=crop&crop=center&auto=format&q=80',
    'https://www.lakearrowheadclub.com',
    '(770) 479-2000',
    '123 Lake Arrowhead Dr',
    'Canton',
    'GA',
    '30114',
    'USA',
    34.2345,
    -84.4567,
    'private',
    0,
    0,
    0,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    'Collared shirts required, no denim',
    true,
    true
),

-- 2. The Club at Lake Arrowhead - Creeks Course (Private)
(
    'The Club at Lake Arrowhead - Creeks Course',
    'Canton, GA',
    'The Creeks Course at Lake Arrowhead features rolling hills, mature hardwoods, and strategic water hazards. Known for its challenging greens and beautiful natural setting.',
    72,
    18,
    4.7,
    76,
    'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=1200&h=800&fit=crop&crop=center&auto=format&q=80',
    'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=200&h=200&fit=crop&crop=center&auto=format&q=80',
    'https://www.lakearrowheadclub.com',
    '(770) 479-2000',
    '123 Lake Arrowhead Dr',
    'Canton',
    'GA',
    '30114',
    'USA',
    34.2345,
    -84.4567,
    'private',
    0,
    0,
    0,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    'Collared shirts required, no denim',
    true,
    true
),

-- 3. The Club at Lake Arrowhead - Lakes Course (Private)
(
    'The Club at Lake Arrowhead - Lakes Course',
    'Canton, GA',
    'The Lakes Course at Lake Arrowhead offers stunning water views and challenging play. Features strategic bunkering and undulating greens with beautiful lakefront holes.',
    72,
    18,
    4.9,
    92,
    'https://images.unsplash.com/photo-1593111774240-d529f12cf4b0?w=1200&h=800&fit=crop&crop=center&auto=format&q=80',
    'https://images.unsplash.com/photo-1593111774240-d529f12cf4b0?w=200&h=200&fit=crop&crop=center&auto=format&q=80',
    'https://www.lakearrowheadclub.com',
    '(770) 479-2000',
    '123 Lake Arrowhead Dr',
    'Canton',
    'GA',
    '30114',
    'USA',
    34.2345,
    -84.4567,
    'private',
    0,
    0,
    0,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    'Collared shirts required, no denim',
    true,
    true
),

-- 4. The Club at Lake Arrowhead - Executive Course (Private)
(
    'The Club at Lake Arrowhead - Executive Course',
    'Canton, GA',
    'A shorter executive course perfect for quick rounds and practice. Features shorter holes with challenging greens and strategic bunkering.',
    60,
    18,
    4.5,
    58,
    'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=1200&h=800&fit=crop&crop=center&auto=format&q=80',
    'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=200&h=200&fit=crop&crop=center&auto=format&q=80',
    'https://www.lakearrowheadclub.com',
    '(770) 479-2000',
    '123 Lake Arrowhead Dr',
    'Canton',
    'GA',
    '30114',
    'USA',
    34.2345,
    -84.4567,
    'private',
    0,
    0,
    0,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    'Collared shirts required, no denim',
    false,
    true
),

-- 5. The Club at Lake Arrowhead - Practice Facility (Private)
(
    'The Club at Lake Arrowhead - Practice Facility',
    'Canton, GA',
    'State-of-the-art practice facility featuring a driving range, short game area, and putting green. Perfect for improving your game with professional instruction.',
    0,
    0,
    4.6,
    45,
    'https://images.unsplash.com/photo-1594736797933-d0401ba2fe65?w=1200&h=800&fit=crop&crop=center&auto=format&q=80',
    'https://images.unsplash.com/photo-1594736797933-d0401ba2fe65?w=200&h=200&fit=crop&crop=center&auto=format&q=80',
    'https://www.lakearrowheadclub.com',
    '(770) 479-2000',
    '123 Lake Arrowhead Dr',
    'Canton',
    'GA',
    '30114',
    'USA',
    34.2345,
    -84.4567,
    'private',
    0,
    0,
    0,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    'Collared shirts required, no denim',
    false,
    true
),

-- 6. The Club at Lake Arrowhead - Clubhouse (Private)
(
    'The Club at Lake Arrowhead - Clubhouse',
    'Canton, GA',
    'Elegant clubhouse featuring fine dining, pro shop, and event facilities. Perfect for hosting tournaments, weddings, and special events.',
    0,
    0,
    4.7,
    38,
    'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=1200&h=800&fit=crop&crop=center&auto=format&q=80',
    'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=200&h=200&fit=crop&crop=center&auto=format&q=80',
    'https://www.lakearrowheadclub.com',
    '(770) 479-2000',
    '123 Lake Arrowhead Dr',
    'Canton',
    'GA',
    '30114',
    'USA',
    34.2345,
    -84.4567,
    'private',
    0,
    0,
    0,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    'Collared shirts required, no denim',
    false,
    true
),

-- 7. The Club at Lake Arrowhead - Tennis Courts (Private)
(
    'The Club at Lake Arrowhead - Tennis Courts',
    'Canton, GA',
    'Professional tennis courts with lighting for evening play. Features both hard and clay courts with professional instruction available.',
    0,
    0,
    4.4,
    32,
    'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=1200&h=800&fit=crop&crop=center&auto=format&q=80',
    'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=200&h=200&fit=crop&crop=center&auto=format&q=80',
    'https://www.lakearrowheadclub.com',
    '(770) 479-2000',
    '123 Lake Arrowhead Dr',
    'Canton',
    'GA',
    '30114',
    'USA',
    34.2345,
    -84.4567,
    'private',
    0,
    0,
    0,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    'Collared shirts required, no denim',
    false,
    true
),

-- 8. The Club at Lake Arrowhead - Swimming Pool (Private)
(
    'The Club at Lake Arrowhead - Swimming Pool',
    'Canton, GA',
    'Olympic-sized swimming pool with diving board and children\'s area. Perfect for family recreation and summer activities.',
    0,
    0,
    4.3,
    28,
    'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=1200&h=800&fit=crop&crop=center&auto=format&q=80',
    'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=200&h=200&fit=crop&crop=center&auto=format&q=80',
    'https://www.lakearrowheadclub.com',
    '(770) 479-2000',
    '123 Lake Arrowhead Dr',
    'Canton',
    'GA',
    '30114',
    'USA',
    34.2345,
    -84.4567,
    'private',
    0,
    0,
    0,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    'Collared shirts required, no denim',
    false,
    true
),

-- 9. The Club at Lake Arrowhead - Fitness Center (Private)
(
    'The Club at Lake Arrowhead - Fitness Center',
    'Canton, GA',
    'Fully equipped fitness center with cardio equipment, weight training, and group fitness classes. Personal training available.',
    0,
    0,
    4.5,
    35,
    'https://images.unsplash.com/photo-1594736797933-d0401ba2fe65?w=1200&h=800&fit=crop&crop=center&auto=format&q=80',
    'https://images.unsplash.com/photo-1594736797933-d0401ba2fe65?w=200&h=200&fit=crop&crop=center&auto=format&q=80',
    'https://www.lakearrowheadclub.com',
    '(770) 479-2000',
    '123 Lake Arrowhead Dr',
    'Canton',
    'GA',
    '30114',
    'USA',
    34.2345,
    -84.4567,
    'private',
    0,
    0,
    0,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    'Collared shirts required, no denim',
    false,
    true
),

-- 10. The Club at Lake Arrowhead - Marina (Private)
(
    'The Club at Lake Arrowhead - Marina',
    'Canton, GA',
    'Full-service marina with boat slips, fuel, and maintenance. Perfect for water sports and lake recreation.',
    0,
    0,
    4.6,
    41,
    'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=1200&h=800&fit=crop&crop=center&auto=format&q=80',
    'https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=200&h=200&fit=crop&crop=center&auto=format&q=80',
    'https://www.lakearrowheadclub.com',
    '(770) 479-2000',
    '123 Lake Arrowhead Dr',
    'Canton',
    'GA',
    '30114',
    'USA',
    34.2345,
    -84.4567,
    'private',
    0,
    0,
    0,
    true,
    true,
    true,
    true,
    true,
    true,
    true,
    'Collared shirts required, no denim',
    false,
    true
);

-- Verify the data was inserted
SELECT 
    name,
    location,
    course_type,
    par,
    holes,
    average_rating,
    review_count,
    green_fees_min,
    green_fees_max
FROM golf_courses 
WHERE state = 'GA' AND city = 'Canton'
ORDER BY average_rating DESC, name;

-- Show summary
SELECT 
    'Canton, Georgia Golf Courses Added Successfully' AS status,
    COUNT(*) AS total_courses,
    COUNT(CASE WHEN course_type = 'private' THEN 1 END) AS private_courses,
    COUNT(CASE WHEN course_type = 'public' THEN 1 END) AS public_courses,
    COUNT(CASE WHEN is_featured = true THEN 1 END) AS featured_courses
FROM golf_courses 
WHERE state = 'GA' AND city = 'Canton';
