#!/bin/bash

echo "🔧 Fixing user_profiles table schema..."
echo "======================================"
echo ""
echo "This script will add missing columns to the user_profiles table"
echo "to fix the 'experience_level' column error and other missing fields."
echo ""
echo "📋 Missing columns that will be added:"
echo "  - header_image_url (TEXT)"
echo "  - home_club (TEXT)"
echo "  - years_playing (INTEGER)"
echo "  - favorite_course (TEXT)"
echo "  - playing_style (TEXT)"
echo "  - goals (TEXT)"
echo "  - experience_level (TEXT)"
echo "  - preferred_playing_days (TEXT[])"
echo "  - preferred_playing_times (TEXT[])"
echo "  - golf_goals (TEXT[])"
echo "  - total_points (INTEGER)"
echo "  - member_since (TIMESTAMP)"
echo ""
echo "🚀 Instructions:"
echo "1. Go to your Supabase dashboard"
echo "2. Navigate to the SQL Editor"
echo "3. Choose one of the SQL scripts:"
echo "   - fix-user-profiles-schema-simple.sql (recommended - no constraints)"
echo "   - fix-user-profiles-schema.sql (full version with constraints)"
echo "4. Copy and paste the contents of your chosen script"
echo "5. Run the SQL script"
echo "6. Verify the schema update was successful"
echo ""
echo "📁 SQL files available:"
echo "   - fix-user-profiles-schema-simple.sql (simple, no constraints)"
echo "   - fix-user-profiles-schema.sql (full version with constraints)"
echo ""
echo "✅ After running the SQL script, the profile update errors should be resolved!"
echo ""
echo "🔍 To verify the fix worked:"
echo "   - Try updating your profile in the app"
echo "   - Check that no more 'experience_level' column errors appear"
echo "   - Verify all profile fields can be saved successfully"
