#!/bin/bash

echo "🔗 Setting up user_connections table for golf community..."
echo ""
echo "📋 Instructions:"
echo "1. Go to your Supabase dashboard"
echo "2. Navigate to the SQL Editor"
echo "3. Copy and paste the contents of 'create-user-connections-table.sql'"
echo "4. Click 'Run' to execute the SQL"
echo ""
echo "📄 The SQL file contains:"
echo "   - user_connections table creation"
echo "   - connection_status enum type"
echo "   - notifications table creation"
echo "   - notification_type enum type"
echo "   - RLS policies for security"
echo "   - Proper indexes for performance"
echo ""
echo "✅ After running the SQL, the connections feature should work!"
echo ""
echo "🔍 To verify it worked, check that these tables exist:"
echo "   - user_connections"
echo "   - notifications"
echo ""
echo "📁 SQL file location: create-user-connections-table.sql"
