#!/bin/bash

echo "🔧 Fixing user_profiles table schema..."
echo "======================================"
echo ""
echo "This script will add missing columns to the user_profiles table"
echo "to fix the 'experience_level' column error and other missing fields."
echo ""
echo "📋 Missing columns that will be added:"
echo "  - header_image_url (TEXT)"
echo "  - home_club (TEXT)"
echo "  - years_playing (INTEGER)"
echo "  - favorite_course (TEXT)"
echo "  - playing_style (TEXT)"
echo "  - goals (TEXT)"
echo "  - experience_level (TEXT)"
echo "  - preferred_playing_days (TEXT[])"
echo "  - preferred_playing_times (TEXT[])"
echo "  - golf_goals (TEXT[])"
echo "  - total_points (INTEGER)"
echo "  - member_since (TIMESTAMP)"
echo ""
echo "🚀 Instructions:"
echo "1. Go to your Supabase dashboard"
echo "2. Navigate to the SQL Editor"
echo "3. Copy and paste the contents of 'fix-user-profiles-schema.sql'"
echo "4. Run the SQL script"
echo "5. Verify the schema update was successful"
echo ""
echo "📁 SQL file location: fix-user-profiles-schema.sql"
echo ""
echo "✅ After running the SQL script, the profile update errors should be resolved!"
echo ""
echo "🔍 To verify the fix worked:"
echo "   - Try updating your profile in the app"
echo "   - Check that no more 'experience_level' column errors appear"
echo "   - Verify all profile fields can be saved successfully"
