#!/bin/bash

echo "🏌️ Fixing Tee Time Applications Schema..."
echo "=========================================="
echo ""
echo "This script will fix the missing 'updated_at' column in the tee_time_applications table"
echo "that's causing 400 errors when accepting tee time applications."
echo ""
echo "📋 What this fixes:"
echo "  - Adds missing 'updated_at' column to tee_time_applications table"
echo "  - Updates existing records with proper timestamps"
echo "  - Creates performance indexes"
echo "  - Resolves 'Could not find updated_at column' error"
echo ""
echo "🚀 Instructions:"
echo "1. Go to your Supabase dashboard"
echo "2. Navigate to the SQL Editor"
echo "3. Copy and paste the contents of 'fix-tee-time-applications-schema.sql'"
echo "4. Run the SQL script"
echo "5. Verify the schema update was successful"
echo ""
echo "📁 SQL file location: fix-tee-time-applications-schema.sql"
echo ""
echo "✅ After running the SQL script:"
echo "   - Tee time application acceptance will work correctly"
echo "   - No more 400 errors when accepting applications"
echo "   - Updated timestamps will be properly tracked"
echo ""
echo "🔍 To verify the fix worked:"
echo "   - Try accepting a tee time application"
echo "   - Check that no more 'updated_at column' errors appear"
echo "   - Verify applications can be accepted and denied successfully"
